apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Prometheus Dev
    orgId: 1
  - name: Prometheus Prod
    orgId: 1

datasources:
  - name: Prometheus Dev
    type: prometheus
    uid: prometheus-dev
    access: proxy
    url: $PROMETHEUS_DEV_URL
    basicAuth: true
    basicAuthUser: $PROMETHEUS_DEV_BASIC_AUTH_USER
    secureJsonData:
      basicAuthPassword: $PROMETHEUS_DEV_BASIC_AUTH_PASSWORD
    isDefault: true
    editable: false

  - name: Prometheus Prod
    type: prometheus
    uid: prometheus-prod
    access: proxy
    url: $PROMETHEUS_PROD_URL
    basicAuth: true
    basicAuthUser: $PROMETHEUS_PROD_BASIC_AUTH_USER
    secureJsonData:
      basicAuthPassword: $PROMETHEUS_PROD_BASIC_AUTH_PASSWORD
    isDefault: false
    editable: false
