-- ddl-auto(update)로 자연스럽게 자라온 스키마를 Flyway 관리 대상으로 편입시키는 baseline.
-- Hibernate 스키마 export(엔티티 기준, PostgreSQLDialect)로 생성했고 손으로 옮겨 적지 않았다.
-- 이미 테이블이 있는 기존 dev/local/prod 환경은 baseline-on-migrate 설정으로 이 스크립트를
-- 건너뛰고(=재실행 안 됨) V2부터 적용되며, 완전히 빈 새 환경만 이 스크립트로 전체 스키마를 만든다.

    create table activity_log (
        activity_date date not null,
        count integer not null,
        create_date timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        modify_date timestamp(6),
        primary key (id),
        unique (member_id, activity_date)
    );

    create table bookmark (
        create_date timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        modify_date timestamp(6),
        target_id bigint not null,
        target_type varchar(255) not null check ((target_type in ('PARTY','CONTEST','GOAL','PARTY_SHOWCASE'))),
        primary key (id),
        unique (member_id, target_type, target_id)
    );

    create table contest (
        application_period_end date not null,
        application_period_start date not null,
        create_date timestamp(6),
        creator_member_id bigint,
        host_id bigint,
        id bigint generated by default as identity,
        modify_date timestamp(6),
        contest_tag varchar(255) not null check ((contest_tag in ('DATA','ENVIRONMENT','FINTECH','UX','AI','LOCAL_ECONOMY','ETC'))),
        format varchar(255) not null check ((format in ('CONTEST','HACKATHON'))),
        title varchar(255) not null,
        primary key (id)
    );

    create table contest_post (
        like_count integer not null,
        view_count integer not null,
        contest_id bigint not null unique,
        create_date timestamp(6),
        id bigint generated by default as identity,
        modify_date timestamp(6),
        image_url varchar(255),
        link_url varchar(255) not null,
        description oid,
        primary key (id)
    );

    create table github_app_global_install_state (
        consumed_at timestamp(6),
        create_date timestamp(6),
        expires_at timestamp(6) not null,
        id bigint generated by default as identity,
        modify_date timestamp(6),
        requested_by_member_id bigint not null,
        state varchar(128) not null unique,
        primary key (id)
    );

    create table github_app_installation (
        account_github_id bigint not null,
        create_date timestamp(6),
        deleted_at timestamp(6),
        id bigint generated by default as identity,
        installation_id bigint not null unique,
        installed_at timestamp(6),
        installed_by_github_user_id bigint,
        modify_date timestamp(6),
        suspended_at timestamp(6),
        account_login varchar(255) not null,
        account_type varchar(255) not null,
        status varchar(255) not null check ((status in ('ACTIVE','SUSPENDED','DELETED'))),
        primary key (id)
    );

    create table github_app_user_authorization (
        access_token_expires_at timestamp(6) not null,
        create_date timestamp(6),
        github_user_id bigint not null unique,
        id bigint generated by default as identity,
        member_id bigint not null unique,
        modify_date timestamp(6),
        refresh_token_expires_at timestamp(6),
        revoked_at timestamp(6),
        encrypted_access_token oid not null,
        encrypted_refresh_token oid,
        primary key (id)
    );

    create table github_app_user_authorization_state (
        consumed_at timestamp(6),
        create_date timestamp(6),
        expires_at timestamp(6) not null,
        id bigint generated by default as identity,
        member_id bigint not null,
        modify_date timestamp(6),
        state varchar(128) not null unique,
        code_verifier varchar(256) not null,
        primary key (id)
    );

    create table github_installation_repository (
        create_date timestamp(6),
        id bigint generated by default as identity,
        installation_id bigint not null,
        modify_date timestamp(6),
        removed_at timestamp(6),
        repository_id bigint not null,
        full_name varchar(255) not null,
        status varchar(255) not null check ((status in ('AVAILABLE','REMOVED'))),
        primary key (id),
        constraint uk_github_installation_repository unique (installation_id, repository_id)
    );

    create table github_app_install_state (
        consumed_at timestamp(6),
        create_date timestamp(6),
        expires_at timestamp(6),
        id bigint generated by default as identity,
        modify_date timestamp(6),
        party_id bigint not null unique,
        requested_by_id bigint not null,
        state varchar(128) not null unique,
        redirect_path varchar(2048),
        primary key (id)
    );

    create table github_webhook_delivery (
        create_date timestamp(6),
        id bigint generated by default as identity,
        modify_date timestamp(6),
        delivery_id varchar(255) not null unique,
        primary key (id)
    );

    create table goal (
        like_count integer not null,
        create_date timestamp(6),
        id bigint generated by default as identity,
        modify_date timestamp(6),
        owner_id bigint not null,
        party_assemble_to_member_id bigint,
        source_party_id bigint,
        source varchar(255) not null check ((source in ('SELF_REPORTED','PLATFORM_VERIFIED'))),
        status varchar(255) not null check ((status in ('WANT','IN_PROGRESS','HOLD','ACHIEVED'))),
        type varchar(255) not null check ((type in ('PROJECT','CONTEST','CHECKLIST'))),
        primary key (id),
        unique (party_assemble_to_member_id)
    );

    create table keyword_related_term (
        create_date timestamp(6),
        id bigint generated by default as identity,
        modify_date timestamp(6),
        related_term varchar(255),
        term varchar(255),
        primary key (id),
        unique (term, related_term)
    );

    create table keyword_synonym (
        create_date timestamp(6),
        id bigint generated by default as identity,
        modify_date timestamp(6),
        canonical_term varchar(255) not null,
        term varchar(255) not null,
        primary key (id),
        unique (term)
    );

    create table like_action (
        create_date timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        modify_date timestamp(6),
        target_id bigint not null,
        target_type varchar(255) not null check ((target_type in ('PARTY','CONTEST','GOAL','PARTY_SHOWCASE'))),
        primary key (id),
        unique (member_id, target_type, target_id)
    );

    create table member (
        active boolean not null,
        create_date timestamp(6),
        github_user_id bigint unique,
        host_id bigint,
        id bigint generated by default as identity,
        last_login_at timestamp(6),
        modify_date timestamp(6),
        api_key varchar(255) unique,
        email varchar(255) unique,
        github_email varchar(255),
        github_provider_user_id varchar(255) unique,
        name varchar(255),
        password varchar(255),
        profile_img_url varchar(255),
        role varchar(255) check ((role in ('MEMBER','ADMIN','HOST'))),
        primary key (id)
    );

    create table member_profile (
        create_date timestamp(6),
        id bigint generated by default as identity,
        member_id bigint unique,
        modify_date timestamp(6),
        bio varchar(1000),
        nickname varchar(255),
        position varchar(255) check ((position in ('BACK','FRONT','UIUX','PM'))),
        profile_image_url varchar(255),
        web_page varchar(255),
        primary key (id),
        constraint uk_member_profile_nickname unique (nickname)
    );

    create table member_profile_career (
        end_date date,
        start_date date,
        create_date timestamp(6),
        id bigint generated by default as identity,
        member_profile_id bigint not null,
        modify_date timestamp(6),
        description varchar(1000),
        org varchar(255),
        role varchar(255) not null,
        primary key (id)
    );

    create table member_profile_link (
        create_date timestamp(6),
        id bigint generated by default as identity,
        member_profile_id bigint not null,
        modify_date timestamp(6),
        url varchar(2048) not null,
        label varchar(255) not null,
        primary key (id)
    );

    create table member_profile_tech_stack (
        create_date timestamp(6),
        id bigint generated by default as identity,
        member_profile_id bigint not null,
        modify_date timestamp(6),
        tech_stack varchar(255),
        primary key (id)
    );

    create table message (
        is_read boolean not null,
        create_date timestamp(6),
        id bigint generated by default as identity,
        modify_date timestamp(6),
        recipient_id bigint not null,
        sender_id bigint not null,
        content varchar(1000) not null,
        primary key (id)
    );

    create table notification (
        is_read boolean not null,
        create_date timestamp(6),
        id bigint generated by default as identity,
        member_id bigint,
        modify_date timestamp(6),
        content varchar(255),
        type varchar(255) check ((type in ('PARTY_APPLICATION_APPROVED','PARTY_APPLICATION_RECEIVED','PARTY_ASSEMBLED','PARTY_COMPLETED','PARTY_SHOWCASE_PUBLISHED'))),
        primary key (id)
    );

    create table party (
        like_count integer not null,
        view_count integer not null,
        completed_at timestamp(6),
        create_date timestamp(6),
        deadline timestamp(6) not null,
        id bigint generated by default as identity,
        modify_date timestamp(6),
        owner_id bigint not null,
        target_contest_id bigint,
        contest_link_url varchar(255),
        contest_title varchar(255),
        github_repo_url varchar(255),
        party_name varchar(255) not null,
        party_tag varchar(255) not null check ((party_tag in ('WEB','APP','GAME','ETC'))),
        status varchar(255) not null check ((status in ('RECRUITING','IN_PROGRESS','COMPLETED'))),
        title varchar(255) not null,
        topic_type varchar(255) not null check ((topic_type in ('CONTEST','PROJECT','STUDY','ETC'))),
        description oid,
        primary key (id)
    );

    create table party_github_binding (
        create_date timestamp(6),
        disconnected_at timestamp(6),
        id bigint generated by default as identity,
        installation_repository_id bigint not null,
        linked_at timestamp(6) not null,
        linked_by_member_id bigint not null,
        modify_date timestamp(6),
        party_id bigint not null,
        disconnect_reason varchar(255),
        status varchar(255) not null check ((status in ('SYNCING','ACTIVE','ARCHIVED','DISCONNECTED'))),
        primary key (id)
    );

    create table party_github_binding_audit (
        actor_member_id bigint,
        create_date timestamp(6),
        id bigint generated by default as identity,
        installation_repository_id bigint,
        modify_date timestamp(6),
        party_id bigint not null,
        reason varchar(1000),
        action varchar(255) not null check ((action in ('CONNECTED','DISCONNECTED','ARCHIVED','CONNECTION_REJECTED'))),
        primary key (id)
    );

    create table party_assemble (
        create_date timestamp(6),
        id bigint generated by default as identity,
        modify_date timestamp(6),
        party_id bigint not null unique,
        published_at timestamp(6),
        primary key (id)
    );

    create table party_assemble_to_member (
        create_date timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        modify_date timestamp(6),
        party_assemble_id bigint not null,
        primary key (id)
    );

    create table party_github_connection (
        create_date timestamp(6),
        credential_member_id bigint not null,
        id bigint generated by default as identity,
        installation_id bigint,
        last_synced_at timestamp(6),
        modify_date timestamp(6),
        party_id bigint not null unique,
        repository_id bigint unique,
        webhook_id bigint,
        last_error varchar(2000),
        last_error_code varchar(255),
        repository_full_name varchar(255) not null,
        status varchar(255) not null check ((status in ('PENDING','SYNCING','ACTIVE','ARCHIVED','DISCONNECTED','INSTALLATION_REQUIRED','APPROVAL_PENDING','ERROR'))),
        primary key (id)
    );

    create table party_member (
        create_date timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        modify_date timestamp(6),
        party_id bigint not null,
        position_id bigint not null,
        message varchar(50),
        status varchar(255) not null check ((status in ('PENDING','APPROVED','REJECTED'))),
        primary key (id),
        unique (party_id, member_id)
    );

    create table party_pr (
        draft boolean not null,
        merged boolean not null,
        number integer not null,
        author_github_user_id bigint,
        closed_at timestamp(6) with time zone,
        create_date timestamp(6),
        github_pr_id bigint not null,
        github_updated_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        merged_at timestamp(6) with time zone,
        modify_date timestamp(6),
        opened_at timestamp(6) with time zone,
        party_id bigint not null,
        html_url varchar(1024) not null,
        author_login varchar(255),
        base_branch varchar(255),
        head_branch varchar(255),
        state varchar(255) not null,
        title varchar(255) not null,
        primary key (id),
        constraint uk_party_pr_github_pr unique (party_id, github_pr_id)
    );

    create table party_search_keyword (
        create_date timestamp(6),
        id bigint generated by default as identity,
        modify_date timestamp(6),
        party_id bigint not null unique,
        keywords TEXT,
        primary key (id)
    );

    create table party_showcase (
        like_count integer not null,
        published boolean not null,
        view_count integer not null,
        create_date timestamp(6),
        id bigint generated by default as identity,
        modify_date timestamp(6),
        party_id bigint not null unique,
        published_at timestamp(6),
        title varchar(255),
        description oid,
        primary key (id)
    );

    create table personal_todo (
        create_date timestamp(6),
        id bigint generated by default as identity,
        modify_date timestamp(6),
        owner_id bigint not null,
        category varchar(255) not null check ((category in ('STUDY','SIDE','CAREER','CERTIFICATE','ETC'))),
        memo varchar(255),
        status varchar(255) not null check ((status in ('WANT','IN_PROGRESS','HOLD','ACHIEVED'))),
        title varchar(255) not null,
        primary key (id)
    );

    create table personal_todo_item (
        done boolean not null,
        sort_order integer not null,
        create_date timestamp(6),
        done_at timestamp(6),
        id bigint generated by default as identity,
        modify_date timestamp(6),
        todo_id bigint not null,
        content varchar(255) not null,
        primary key (id)
    );

    create table personal_checklist (
        target_date date,
        goal_id bigint not null,
        personal_todo_id bigint unique,
        memo varchar(255),
        title varchar(255) not null,
        primary key (goal_id)
    );

    create table personal_contest (
        award_date date,
        is_team boolean not null,
        evidence_size bigint,
        goal_id bigint not null,
        target_contest_id bigint,
        contest_url varchar(255),
        evidence_file_name varchar(255),
        evidence_mime_type varchar(255),
        evidence_storage_key varchar(255),
        result varchar(255),
        title varchar(255) not null,
        primary key (goal_id)
    );

    create table position (
        capacity integer not null,
        filled_count integer not null,
        version integer not null,
        create_date timestamp(6),
        id bigint generated by default as identity,
        modify_date timestamp(6),
        party_id bigint not null,
        type varchar(255) not null check ((type in ('BACK','FRONT','UIUX','PM'))),
        primary key (id)
    );

    create table project (
        end_date date,
        start_date date not null,
        goal_id bigint not null,
        party_showcase_id bigint,
        position_type varchar(255) check ((position_type in ('BACK','FRONT','UIUX','PM'))),
        title varchar(255) not null,
        primary key (goal_id)
    );

    create table search_log (
        create_date timestamp(6),
        id bigint generated by default as identity,
        member_id bigint not null,
        modify_date timestamp(6),
        keyword varchar(255),
        primary key (id)
    );

    create index idx_bookmark_target 
       on bookmark (target_type, target_id);

    create index idx_goal_owner 
       on goal (owner_id);

    create index idx_goal_source_party 
       on goal (source_party_id);

    create index idx_keyword_related_term_term 
       on keyword_related_term (term);

    create index idx_like_action_target 
       on like_action (target_type, target_id);

    create index idx_message_recipient_created 
       on message (recipient_id, create_date);

    create index idx_message_sender_created 
       on message (sender_id, create_date);

    create index idx_party_github_connection_installation_id 
       on party_github_connection (installation_id);

    create index idx_party_showcase_published 
       on party_showcase (published);

    create index idx_personal_todo_owner 
       on personal_todo (owner_id);

    create index idx_personal_todo_item_todo 
       on personal_todo_item (todo_id);

    alter table if exists activity_log 
       add constraint FKe4fqqtm3m377ikqjp5rfbkkh1 
       foreign key (member_id) 
       references member;

    alter table if exists bookmark 
       add constraint FK5bm7rup91j277mc7gg63akie2 
       foreign key (member_id) 
       references member;

    alter table if exists contest_post 
       add constraint FKgs14lxptpb7hbcrwabhug9jk6 
       foreign key (contest_id) 
       references contest;

    alter table if exists github_app_global_install_state 
       add constraint FKmaosqjtsiogcviatd6ak0wa3r 
       foreign key (requested_by_member_id) 
       references member;

    alter table if exists github_app_user_authorization 
       add constraint FK97dt3bmsmbojlo65dlnufg10a 
       foreign key (member_id) 
       references member;

    alter table if exists github_app_user_authorization_state 
       add constraint FKiya5ar97xsgn3648vcac5l31d 
       foreign key (member_id) 
       references member;

    alter table if exists github_installation_repository 
       add constraint FKss3xrsu0jr22qt62d5q16ix8q 
       foreign key (installation_id) 
       references github_app_installation;

    alter table if exists github_app_install_state 
       add constraint FKnf5nad73h36lbs9fi2vfdfmsw 
       foreign key (party_id) 
       references party;

    alter table if exists github_app_install_state 
       add constraint FKelhaim0frg4sysxhwko00d0kp 
       foreign key (requested_by_id) 
       references member;

    alter table if exists goal 
       add constraint FK5ftpda795co4ss7s8s1uy0gmk 
       foreign key (owner_id) 
       references member;

    alter table if exists like_action 
       add constraint FK8ss2i01jnj2cnorebg94ksa6o 
       foreign key (member_id) 
       references member;

    alter table if exists member_profile 
       add constraint FKkrtcs7wdtv954e99w88uga9mq 
       foreign key (member_id) 
       references member;

    alter table if exists member_profile_career 
       add constraint FKp7vrfq21hjgc9coctaiell93t 
       foreign key (member_profile_id) 
       references member_profile;

    alter table if exists member_profile_link 
       add constraint FK6l3xnogq1fq8akgcnnjdqlugj 
       foreign key (member_profile_id) 
       references member_profile;

    alter table if exists member_profile_tech_stack 
       add constraint FK1jsapp89nexx00ttu6nbf0sn1 
       foreign key (member_profile_id) 
       references member_profile;

    alter table if exists message 
       add constraint FKiqvl4li2trmmmypihx3n8a8t9 
       foreign key (recipient_id) 
       references member;

    alter table if exists message 
       add constraint FKt23a3aa8rhuah50164n3syecy 
       foreign key (sender_id) 
       references member;

    alter table if exists notification 
       add constraint FK1xep8o2ge7if6diclyyx53v4q 
       foreign key (member_id) 
       references member;

    alter table if exists party 
       add constraint FK8bwr0xqlhovh7fx7a7qxk5hmw 
       foreign key (owner_id) 
       references member;

    alter table if exists party 
       add constraint FK4n9s4xq5px7u331xpqjtmq7t5 
       foreign key (target_contest_id) 
       references contest;

    alter table if exists party_github_binding 
       add constraint FK77krmmei1yiveee6ouf1n503r 
       foreign key (installation_repository_id) 
       references github_installation_repository;

    alter table if exists party_github_binding 
       add constraint FKhby5dnue8y5pr8tey6dl3cpo5 
       foreign key (linked_by_member_id) 
       references member;

    alter table if exists party_github_binding 
       add constraint FKbj8hy6ydjkr5uimdc802wnsy5 
       foreign key (party_id) 
       references party;

    alter table if exists party_github_binding_audit 
       add constraint FKk3wi3qlme4pyn0yanv02njmow 
       foreign key (actor_member_id) 
       references member;

    alter table if exists party_github_binding_audit 
       add constraint FK971fpq36m8g8m3e76sau5n39q 
       foreign key (installation_repository_id) 
       references github_installation_repository;

    alter table if exists party_github_binding_audit 
       add constraint FKfa8am70olt46bud1cy4xki7au 
       foreign key (party_id) 
       references party;

    alter table if exists party_assemble 
       add constraint FK3hbg8tdfycqtbhsml9ghika60 
       foreign key (party_id) 
       references party;

    alter table if exists party_assemble_to_member 
       add constraint FKlvt4y817m92oa2gsggxedw4qe 
       foreign key (member_id) 
       references member;

    alter table if exists party_assemble_to_member 
       add constraint FK47r0otxmdnbuxmij6vwida401 
       foreign key (party_assemble_id) 
       references party_assemble;

    alter table if exists party_github_connection 
       add constraint FKqcy3ts257bt6bfb5710g4gpis 
       foreign key (credential_member_id) 
       references member;

    alter table if exists party_github_connection 
       add constraint FKfe1xmfgh5sm29h1r5qx8rhti9 
       foreign key (party_id) 
       references party;

    alter table if exists party_member 
       add constraint FKnysnaqwxtvpxoos0ycwtklbou 
       foreign key (member_id) 
       references member;

    alter table if exists party_member 
       add constraint FKctrpcp93h130dwe6j1jlhf960 
       foreign key (party_id) 
       references party;

    alter table if exists party_member 
       add constraint FK89nhv7m8xg0t016hd1re9mh7r 
       foreign key (position_id) 
       references position;

    alter table if exists party_pr 
       add constraint FK68nqstna29mfrjw3lohyecjmo 
       foreign key (party_id) 
       references party;

    alter table if exists party_search_keyword 
       add constraint FK16anq97sli0o8mut51b5bwcw8 
       foreign key (party_id) 
       references party;

    alter table if exists party_showcase 
       add constraint FKc86n65exdxt04q3idh06ybqmn 
       foreign key (party_id) 
       references party;

    alter table if exists personal_todo 
       add constraint FKrrihk827hd0nftuaxf3xubyh4 
       foreign key (owner_id) 
       references member;

    alter table if exists personal_todo_item 
       add constraint FKeyuu4urt5cb26j5p3hwgrxdwk 
       foreign key (todo_id) 
       references personal_todo;

    alter table if exists personal_checklist 
       add constraint FK260avfw35fahs0la9ejkyxqj4 
       foreign key (personal_todo_id) 
       references personal_todo;

    alter table if exists personal_checklist 
       add constraint FK1h0ob2yjxgrtvjlejt1dojw0k 
       foreign key (goal_id) 
       references goal;

    alter table if exists personal_contest 
       add constraint FKh1rkpmpb6ifyhkjkb0f7owu9t 
       foreign key (goal_id) 
       references goal;

    alter table if exists position 
       add constraint FKaqkfwi6k3w49o3uieajb5sdvq 
       foreign key (party_id) 
       references party;

    alter table if exists project 
       add constraint FKk1csbryf3rrp9lil6awu8ux84 
       foreign key (party_showcase_id) 
       references party_showcase;

    alter table if exists project 
       add constraint FKbkb3bnywhfkpyt3n94fkxrv8t 
       foreign key (goal_id) 
       references goal;

    alter table if exists search_log 
       add constraint FK9t9ai9txj9j6e7bhg1ih0ukhn 
       foreign key (member_id) 
       references member;
