package com.back.domain.notification.notification.entity;

public enum NotificationType {
    MESSAGE_RECEIVED,
    PARTY_APPLICATION_APPROVED,
    PARTY_APPLICATION_RECEIVED,
    PARTY_RECRUITMENT_COMPLETED,
    PARTY_MATCHING_CONFIRMED,
    PARTY_COMPLETED,
    PARTY_SHOWCASE_PUBLISHED,
    SHOWCASE_COMMENT_CREATED
}
