/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/parties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parties/{partyId}/likes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["likeParty"];
        delete: operations["unlikeParty"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parties/{partyId}/github-app/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["installGithubApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parties/{partyId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parties/{partyId}/close-recruiting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["closeRecruiting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parties/{partyId}/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["apply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/github/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["githubWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 대회 목록 조회 */
        get: operations["list_2"];
        put?: never;
        /** 대회글 작성 */
        post: operations["write"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contests/{contest-id}/likes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["likeContest"];
        delete: operations["unlikeContest"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contests/{contest-id}/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bookmarkContest"];
        delete: operations["unbookmarkContest"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parties/{partyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch: operations["update"];
        trace?: never;
    };
    "/api/v1/parties/{partyId}/applications/{application-id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["decide"];
        trace?: never;
    };
    "/api/v1/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["modifyProfile"];
        trace?: never;
    };
    "/api/v1/contests/{contest-id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 대회 상세 조회 */
        get: operations["getDetail"];
        put?: never;
        post?: never;
        /** 대회글 삭제 */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        /** 대회글 수정 */
        patch: operations["modify"];
        trace?: never;
    };
    "/api/v1/parties/{partyId}/pull-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPullRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parties/{partyId}/github-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGithubConnection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/github-app/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["githubAppSetup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RsDataVoid: {
            resultCode: string;
            msg: string;
            data: unknown;
        };
        PartyCreateReqBody: {
            partyName: string;
            title: string;
            description?: string;
            /** Format: int64 */
            targetContestId?: number;
            contestName?: string;
            contestLinkUrl?: string;
            /** @enum {string} */
            topicType: "CONTEST" | "PROJECT" | "STUDY" | "ETC";
            /** @enum {string} */
            partyTag: "WEB" | "APP" | "GAME" | "ETC";
            githubRepoUrl?: string;
            /** Format: int32 */
            checklistRequiredApprovals?: number;
            /** Format: date-time */
            deadline: string;
            positions: components["schemas"]["PositionReqBody"][];
        };
        PositionReqBody: {
            /** @enum {string} */
            name: "BACK" | "FRONT" | "UIUX" | "PM";
            /** Format: int32 */
            capacity?: number;
        };
        PartyDto: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            ownerId: number;
            ownerName: string;
            partyName: string;
            title: string;
            description: string;
            /** Format: int64 */
            targetContestId: number;
            contestName: string;
            contestLinkUrl: string;
            /** @enum {string} */
            topicType: "CONTEST" | "PROJECT" | "STUDY" | "ETC";
            /** @enum {string} */
            status: "RECRUITING" | "IN_PROGRESS" | "COMPLETED";
            /** @enum {string} */
            partyTag: "WEB" | "APP" | "GAME" | "ETC";
            githubRepoUrl: string;
            /** Format: int32 */
            checklistRequiredApprovals: number;
            /** Format: date-time */
            deadline: string;
            /** Format: int64 */
            dDay: number;
            /** Format: int32 */
            likeCount: number;
            /** Format: int32 */
            viewCount: number;
            positions: components["schemas"]["PositionDto"][];
        };
        PositionDto: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            type: "BACK" | "FRONT" | "UIUX" | "PM";
            /** Format: int32 */
            capacity: number;
            /** Format: int32 */
            filledCount: number;
        };
        RsDataPartyDto: {
            resultCode: string;
            msg: string;
            data: components["schemas"]["PartyDto"];
        };
        LikeDto: {
            /** @enum {string} */
            targetType: "PARTY" | "CONTEST" | "GOAL";
            /** Format: int64 */
            targetId: number;
            liked: boolean;
            /** Format: int32 */
            likeCount: number;
        };
        RsDataLikeDto: {
            resultCode: string;
            msg: string;
            data: components["schemas"]["LikeDto"];
        };
        GithubAppInstallUrlDto: {
            installationUrl: string;
            state: string;
        };
        RsDataGithubAppInstallUrlDto: {
            resultCode: string;
            msg: string;
            data: components["schemas"]["GithubAppInstallUrlDto"];
        };
        ApplyReqBody: {
            /** Format: int64 */
            positionId: number;
            message?: string;
        };
        MemberSignupReqBody: {
            email: string;
            password: string;
            name: string;
        };
        MemberDto: {
            /** Format: int64 */
            id: number;
            email: string;
        };
        RsDataMemberDto: {
            resultCode: string;
            msg: string;
            data: components["schemas"]["MemberDto"];
        };
        RefreshTokenReqBody: {
            refreshToken: string;
        };
        MemberLoginDto: {
            accessToken: string;
            refreshToken: string;
            role: string;
            grantType: string;
            /** Format: int32 */
            accessTokenExpiresIn: number;
        };
        RsDataMemberLoginDto: {
            resultCode: string;
            msg: string;
            data: components["schemas"]["MemberLoginDto"];
        };
        MemberLoginReqBody: {
            email: string;
            password: string;
        };
        ContestWriteReqBody: {
            title: string;
            /** @enum {string} */
            format: "CONTEST" | "HACKATHON";
            /** @enum {string} */
            contestTag: "DATA" | "ENVIRONMENT" | "FINTECH" | "UX" | "AI" | "LOCAL_ECONOMY" | "ETC";
            /** Format: date */
            applicationPeriodStart: string;
            /** Format: date */
            applicationPeriodEnd: string;
            description?: string;
            imageUrl?: string;
            linkUrl: string;
        };
        ContestResponseDto: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            hostId: number;
            /** Format: int64 */
            creatorMemberId: number;
            title: string;
            /** @enum {string} */
            format: "CONTEST" | "HACKATHON";
            /** @enum {string} */
            contestTag: "DATA" | "ENVIRONMENT" | "FINTECH" | "UX" | "AI" | "LOCAL_ECONOMY" | "ETC";
            /** Format: date */
            applicationPeriodStart: string;
            /** Format: date */
            applicationPeriodEnd: string;
            archived: boolean;
            description: string;
            imageUrl: string;
            linkUrl: string;
            /** Format: int32 */
            likeCount: number;
            /** Format: int32 */
            viewCount: number;
            bookmarkedByMe: boolean;
            likedByMe: boolean;
            /** Format: date-time */
            createDate: string;
        };
        RsDataContestResponseDto: {
            resultCode: string;
            msg: string;
            data: components["schemas"]["ContestResponseDto"];
        };
        BookmarkDto: {
            /** @enum {string} */
            targetType: "PARTY" | "CONTEST" | "GOAL";
            /** Format: int64 */
            targetId: number;
            bookmarked: boolean;
        };
        RsDataBookmarkDto: {
            resultCode: string;
            msg: string;
            data: components["schemas"]["BookmarkDto"];
        };
        PartyUpdateReqBody: {
            partyName: string;
            title: string;
            description?: string;
            /** Format: int64 */
            targetContestId?: number;
            contestName?: string;
            contestLinkUrl?: string;
            /** @enum {string} */
            topicType: "CONTEST" | "PROJECT" | "STUDY" | "ETC";
            /** @enum {string} */
            partyTag: "WEB" | "APP" | "GAME" | "ETC";
            githubRepoUrl?: string;
            /** Format: date-time */
            deadline: string;
            positions?: components["schemas"]["PositionCapacityReqBody"][];
        };
        PositionCapacityReqBody: {
            /** Format: int64 */
            positionId: number;
            /** Format: int32 */
            capacity?: number;
        };
        DecisionReqBody: {
            /** @enum {string} */
            pending: "APPROVED" | "REJECTED";
        };
        PartyApplicationDto: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            partyId: number;
            /** Format: int64 */
            applicantId: number;
            applicantName: string;
            /** Format: int64 */
            positionId: number;
            /** @enum {string} */
            positionType: "BACK" | "FRONT" | "UIUX" | "PM";
            /** @enum {string} */
            status: "PENDING" | "APPROVED" | "REJECTED";
            message: string;
            /** Format: date-time */
            createDate: string;
        };
        RsDataPartyApplicationDto: {
            resultCode: string;
            msg: string;
            data: components["schemas"]["PartyApplicationDto"];
        };
        ModifyProfileReqBody: {
            nickname: string;
            webpage?: string;
            profileImageUrl?: string;
            positions: string[];
            techStacks: string[];
        };
        MemberProfileDto: {
            /** Format: int64 */
            id: number;
            email: string;
            name: string;
            nickname: string;
            webpage: string;
            profileImageUrl: string;
            positions: string[];
            techStacks: string[];
        };
        RsDataMemberProfileDto: {
            resultCode: string;
            msg: string;
            data: components["schemas"]["MemberProfileDto"];
        };
        ContestModifyReqBody: {
            title: string;
            description?: string;
            /** Format: date */
            applicationPeriodStart: string;
            /** Format: date */
            applicationPeriodEnd: string;
            linkUrl: string;
            imageUrl?: string;
        };
        PagePartyListItemDto: {
            /** Format: int32 */
            totalPages: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            size: number;
            content: components["schemas"]["PartyListItemDto"][];
            /** Format: int32 */
            number: number;
            sort: components["schemas"]["SortObject"];
            pageable: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements: number;
            first: boolean;
            last: boolean;
            empty: boolean;
        };
        PageableObject: {
            paged: boolean;
            /** Format: int32 */
            pageNumber: number;
            /** Format: int32 */
            pageSize: number;
            sort: components["schemas"]["SortObject"];
            unpaged: boolean;
            /** Format: int64 */
            offset: number;
        };
        PartyListItemDto: {
            /** Format: int64 */
            id: number;
            ownerName: string;
            partyName: string;
            title: string;
            /** @enum {string} */
            topicType: "CONTEST" | "PROJECT" | "STUDY" | "ETC";
            /** @enum {string} */
            status: "RECRUITING" | "IN_PROGRESS" | "COMPLETED";
            /** @enum {string} */
            partyTag: "WEB" | "APP" | "GAME" | "ETC";
            /** Format: date-time */
            deadline: string;
            /** Format: int64 */
            dDay: number;
            /** Format: int32 */
            likeCount: number;
            /** Format: int32 */
            viewCount: number;
            positions: components["schemas"]["PositionDto"][];
        };
        RsDataPagePartyListItemDto: {
            resultCode: string;
            msg: string;
            data: components["schemas"]["PagePartyListItemDto"];
        };
        SortObject: {
            sorted: boolean;
            unsorted: boolean;
            empty: boolean;
        };
        PartyPrDto: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            githubPrId: number;
            /** Format: int32 */
            number: number;
            title: string;
            htmlUrl: string;
            state: string;
            authorLogin: string;
            draft: boolean;
            merged: boolean;
            baseBranch: string;
            headBranch: string;
            /** Format: date-time */
            openedAt: string;
            /** Format: date-time */
            closedAt: string;
            /** Format: date-time */
            mergedAt: string;
            /** Format: date-time */
            githubUpdatedAt: string;
        };
        RsDataListPartyPrDto: {
            resultCode: string;
            msg: string;
            data: components["schemas"]["PartyPrDto"][];
        };
        PartyGithubConnectionDto: {
            status: string;
            repositoryFullName: string;
            lastErrorCode: string;
            lastError: string;
        };
        RsDataPartyGithubConnectionDto: {
            resultCode: string;
            msg: string;
            data: components["schemas"]["PartyGithubConnectionDto"];
        };
        RsDataListPartyApplicationDto: {
            resultCode: string;
            msg: string;
            data: components["schemas"]["PartyApplicationDto"][];
        };
        PageContestResponseDto: {
            /** Format: int32 */
            totalPages: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            size: number;
            content: components["schemas"]["ContestResponseDto"][];
            /** Format: int32 */
            number: number;
            sort: components["schemas"]["SortObject"];
            pageable: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements: number;
            first: boolean;
            last: boolean;
            empty: boolean;
        };
        RsDataPageContestResponseDto: {
            resultCode: string;
            msg: string;
            data: components["schemas"]["PageContestResponseDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: {
                keyword?: string;
                partyTag?: "WEB" | "APP" | "GAME" | "ETC";
                position?: "BACK" | "FRONT" | "UIUX" | "PM";
                sort?: "VACANCY" | "DEADLINE" | "POPULAR";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataPagePartyListItemDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartyCreateReqBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataPartyDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    likeParty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataLikeDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    unlikeParty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    installGithubApp: {
        parameters: {
            query?: {
                redirectUrl?: string;
            };
            header?: never;
            path: {
                partyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataGithubAppInstallUrlDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataPartyDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    closeRecruiting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataPartyDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataListPartyApplicationDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    apply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partyId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyReqBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberSignupReqBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataMemberDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenReqBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataMemberLoginDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberLoginReqBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataMemberLoginDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    githubWebhook: {
        parameters: {
            query?: never;
            header?: {
                "X-GitHub-Event"?: string;
                "X-Hub-Signature-256"?: string;
                "X-GitHub-Delivery"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                format?: "CONTEST" | "HACKATHON";
                contestTag?: "DATA" | "ENVIRONMENT" | "FINTECH" | "UX" | "AI" | "LOCAL_ECONOMY" | "ETC";
                sort?: "LATEST" | "POPULAR" | "DEADLINE";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataPageContestResponseDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    write: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContestWriteReqBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataContestResponseDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    likeContest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "contest-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataLikeDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    unlikeContest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "contest-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    bookmarkContest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "contest-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataBookmarkDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    unbookmarkContest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "contest-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataPartyDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partyId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartyUpdateReqBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataPartyDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    decide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partyId: number;
                "application-id": number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionReqBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataPartyApplicationDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataMemberProfileDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    modifyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModifyProfileReqBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataMemberProfileDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    getDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "contest-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataContestResponseDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "contest-id": number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    modify: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "contest-id": number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContestModifyReqBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataContestResponseDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    getPullRequests: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataListPartyPrDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    getGithubConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataPartyGithubConnectionDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    githubAppSetup: {
        parameters: {
            query: {
                state: string;
                installation_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
}
