server:
  forward-headers-strategy: native
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: back
  profiles:
    default: dev
    group:
      local: compose
      prod: compose
  docker:
    compose:
      enabled: false
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      auto-commit: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${SPRING__SECURITY__OAUTH2__CLIENT__REGISTRATION__GITHUB__CLIENT_ID}
            client-secret: ${SPRING__SECURITY__OAUTH2__CLIENT__REGISTRATION__GITHUB__CLIENT_SECRET}
            client-name: Github
            scope: read:user, user:email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            user-name-attribute: id
springdoc:
  default-produces-media-type: application/json;charset=UTF-8
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
custom:
  frontend:
    base-url: ${CUSTOM__FRONTEND__BASE_URL:/}
  jwt:
    secretKey: ${CUSTOM__JWT__SECRET_KEY:abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890}
  accessToken:
    expirationSeconds: ${CUSTOM__ACCESS_TOKEN__EXPIRATION_SECONDS:900}
  github:
    app:
      id: ${CUSTOM__GITHUB__APP__ID:}
      slug: ${CUSTOM__GITHUB__APP__SLUG:}
      privateKey: ${CUSTOM__GITHUB__APP__PRIVATE_KEY:}
    webhook:
      secret: ${CUSTOM__GITHUB__WEBHOOK__SECRET:}
  notProdMembers:
    - username: KAKAO__4707664779
      apiKey: kakao__1
      nickname: 장희성
      profileImgUrl: http://img1.kakaocdn.net/thumb/R640x640.q70/?fname=http://t1.kakaocdn.net/account_images/default_profile.jpeg
    - username: GOOGLE__103240209825008011930
      apiKey: google__1
      nickname: 몰입코딩(개발자 희성)
      profileImgUrl: https://lh3.googleusercontent.com/a/ACg8ocKClYFeK9VXN6ROFvx-ddTpt0ep30M3TZwaKk1esQrbEtzuqoC2=s96-c
    - username: NAVER__zHNGxuWh88o7a2XxKF2hy76PORvCx87TKtpVS_IHl6k
      apiKey: naver__1
      nickname: 희성
      profileImgUrl: https://phinf.pstatic.net/contact/profile/blog/22/6/jangka44.jpg
