spring:
  docker:
    compose:
      enabled: true
      lifecycle-management: start-and-stop
      stop:
        command: down
  datasource:
    url: jdbc:h2:./db_dev;MODE=PostgreSQL;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
